// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VerificationWebApp.DbModels
{
    [Table("Linkage")]
    public partial class Linkage
    {
        [Key]
        [Column("linkageId")]
        public int LinkageId { get; set; }
        [Column("customerNo")]
        [StringLength(50)]
        public string CustomerNo { get; set; }
        [Column("customerName")]
        [StringLength(50)]
        public string CustomerName { get; set; }
        [Column("nationalId")]
        [StringLength(50)]
        public string NationalId { get; set; }
        [Column("cardValidFrom")]
        [StringLength(50)]
        public string CardValidFrom { get; set; }
        [Column("cardValidTo")]
        [StringLength(50)]
        public string CardValidTo { get; set; }
        [Column("shortGuid")]
        [StringLength(50)]
        public string ShortGuid { get; set; }
        [Column("createdById")]
        public int? CreatedById { get; set; }
        [Column("createdDate", TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("lastUpdatedById")]
        public int? LastUpdatedById { get; set; }
        [Column("lastUpdatedDate", TypeName = "datetime")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}