// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VerificationWebApp.DbModels
{
    [Table("Log")]
    public partial class Log
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("ref")]
        [StringLength(50)]
        public string Ref { get; set; }
        [Column("rawdata", TypeName = "ntext")]
        public string Rawdata { get; set; }
    }
}