// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VerificationWebApp.DbModels
{
    [Table("Response")]
    public partial class Response
    {
        [Key]
        [Column("responseId")]
        public int ResponseId { get; set; }
        [Column("nationalId")]
        [StringLength(50)]
        public string NationalId { get; set; }
        [Column("cardId")]
        [StringLength(50)]
        public string CardId { get; set; }
        [Column("cardValidFrom")]
        [StringLength(50)]
        public string CardValidFrom { get; set; }
        [Column("cardValidTo")]
        [StringLength(50)]
        public string CardValidTo { get; set; }
        [Column("surname")]
        [StringLength(50)]
        public string Surname { get; set; }
        [Column("forenames")]
        [StringLength(50)]
        public string Forenames { get; set; }
        [Column("nationality")]
        [StringLength(50)]
        public string Nationality { get; set; }
        [Column("birthDate")]
        [StringLength(50)]
        public string BirthDate { get; set; }
        [Column("gender")]
        [StringLength(50)]
        public string Gender { get; set; }
        [Column("digitalAddress")]
        [StringLength(50)]
        public string DigitalAddress { get; set; }
        [Column("postalCode")]
        [StringLength(50)]
        public string PostalCode { get; set; }
        [Column("occupation")]
        [StringLength(50)]
        public string Occupation { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("phoneNumber")]
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        [Column("phoneNumberType")]
        [StringLength(50)]
        public string PhoneNumberType { get; set; }
        [Column("phoneNumberNetwork")]
        [StringLength(50)]
        public string PhoneNumberNetwork { get; set; }
        [Column("biometricFeedData", TypeName = "ntext")]
        public string BiometricFeedData { get; set; }
        [Column("biometricFeedDataType")]
        [StringLength(50)]
        public string BiometricFeedDataType { get; set; }
        [Column("transactionGuid")]
        [StringLength(50)]
        public string TransactionGuid { get; set; }
        [Column("shortGuid")]
        [StringLength(50)]
        public string ShortGuid { get; set; }
        [Column("requestTimestamp")]
        [StringLength(50)]
        public string RequestTimestamp { get; set; }
        [Column("responseTimestamp")]
        [StringLength(50)]
        public string ResponseTimestamp { get; set; }
        [Column("verified")]
        [StringLength(50)]
        public string Verified { get; set; }
        [Column("onWatchList")]
        [StringLength(50)]
        public string OnWatchList { get; set; }
        [Column("success")]
        [StringLength(50)]
        public string Success { get; set; }
        [Column("center")]
        [StringLength(50)]
        public string Center { get; set; }
        [Column("userId")]
        [StringLength(50)]
        public string UserId { get; set; }
        [Column("rawData", TypeName = "ntext")]
        public string RawData { get; set; }
        [Column("createdById")]
        public int? CreatedById { get; set; }
        [Column("createdDate", TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("lastUpdatedById")]
        public int? LastUpdatedById { get; set; }
        [Column("lastUpdatedDate", TypeName = "datetime")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}